# Generated by Django 3.1.2 on 2020-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0002_device_prognosedprice_region_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrognosedEmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minutes5DK', models.DateTimeField()),
                ('CO2Emission', models.IntegerField()),
                ('PriceArea', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RenameField(
            model_name='prognosedprice',
            old_name='date_time',
            new_name='HourDK',
        ),
        migrations.RenameField(
            model_name='prognosedprice',
            old_name='area',
            new_name='PriceArea',
        ),
        migrations.RenameField(
            model_name='prognosedprice',
            old_name='price',
            new_name='SpotPriceEUR',
        ),
        migrations.AlterUniqueTogether(
            name='prognosedprice',
            unique_together={('HourDK', 'PriceArea')},
        ),
    ]
