# Generated by Django 3.1.2 on 2020-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0003_auto_20201020_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField()),
                ('completed_before', models.DateTimeField()),
                ('time_to_complete', models.IntegerField()),
                ('allowed_on_time', models.CharField(default='', max_length=15)),
                ('energy_consumption', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
