# Generated by Django 3.1.2 on 2020-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0005_auto_20201023_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prognosedprice',
            old_name='SpotPriceEUR',
            new_name='SpotPriceDKK',
        ),
    ]
