# Generated by Django 3.1.2 on 2020-10-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0008_auto_20201026_1411'),
        ('sustainable_power', '0008_auto_20201028_1506'),
    ]

    operations = [
    ]
