# Generated by Django 3.1.2 on 2020-11-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0012_auto_20201104_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
