# Generated by Django 3.1.2 on 2020-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0015_auto_20201109_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bluetooth_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='value',
            name='increase_decrease',
            field=models.BooleanField(null=True),
        ),
    ]
