# Generated by Django 3.1.2 on 2020-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0016_auto_20201111_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='preferred_emission',
            field=models.FloatField(default=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='preferred_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
