# Generated by Django 3.1.2 on 2020-11-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0018_auto_20201111_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prognosedemission',
            unique_together={('Minutes5DK', 'PriceArea')},
        ),
    ]
