# Generated by Django 3.1.2 on 2020-11-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0019_auto_20201119_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emission',
            unique_together={('Minutes5DK', 'PriceArea')},
        ),
    ]
