# Generated by Django 3.1.2 on 2020-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_power', '0020_auto_20201120_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='completed_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='time_to_complete',
            field=models.IntegerField(null=True),
        ),
    ]
